/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CompanyPoliciesRouteImport } from './routes/company-policies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MoreInfoRouteImport } from './routes/more-info'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ExportToRegionRouteImport } from './routes/export-to.$region'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as SeoSlugRouteImport } from './routes/seo.$slug'
import { Route as ApiAdminContentRouteImport } from './routes/api.admin.content'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPoliciesRoute = CompanyPoliciesRouteImport.update({
  id: '/company-policies',
  path: '/company-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreInfoRoute = MoreInfoRouteImport.update({
  id: '/more-info',
  path: '/more-info',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportToRegionRoute = ExportToRegionRouteImport.update({
  id: '/export-to/$region',
  path: '/export-to/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoSlugRoute = SeoSlugRouteImport.update({
  id: '/seo/$slug',
  path: '/seo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentRoute = ApiAdminContentRouteImport.update({
  id: '/api/admin/content',
  path: '/api/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/company-policies': typeof CompanyPoliciesRoute
  '/contact': typeof ContactRoute
  '/more-info': typeof MoreInfoRoute
  '/request-quote': typeof RequestQuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/export-to/$region': typeof ExportToRegionRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/seo/$slug': typeof SeoSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/admin/content': typeof ApiAdminContentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/company-policies': typeof CompanyPoliciesRoute
  '/contact': typeof ContactRoute
  '/more-info': typeof MoreInfoRoute
  '/request-quote': typeof RequestQuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/export-to/$region': typeof ExportToRegionRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/seo/$slug': typeof SeoSlugRoute
  '/blog': typeof BlogIndexRoute
  '/products': typeof ProductsIndexRoute
  '/api/admin/content': typeof ApiAdminContentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/company-policies': typeof CompanyPoliciesRoute
  '/contact': typeof ContactRoute
  '/more-info': typeof MoreInfoRoute
  '/request-quote': typeof RequestQuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/export-to/$region': typeof ExportToRegionRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/seo/$slug': typeof SeoSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/admin/content': typeof ApiAdminContentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/company-policies'
    | '/contact'
    | '/more-info'
    | '/request-quote'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/export-to/$region'
    | '/products/$slug'
    | '/seo/$slug'
    | '/blog/'
    | '/products/'
    | '/api/admin/content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/company-policies'
    | '/contact'
    | '/more-info'
    | '/request-quote'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/export-to/$region'
    | '/products/$slug'
    | '/seo/$slug'
    | '/blog'
    | '/products'
    | '/api/admin/content'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/company-policies'
    | '/contact'
    | '/more-info'
    | '/request-quote'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/export-to/$region'
    | '/products/$slug'
    | '/seo/$slug'
    | '/blog/'
    | '/products/'
    | '/api/admin/content'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CompanyPoliciesRoute: typeof CompanyPoliciesRoute
  ContactRoute: typeof ContactRoute
  MoreInfoRoute: typeof MoreInfoRoute
  RequestQuoteRoute: typeof RequestQuoteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ExportToRegionRoute: typeof ExportToRegionRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  SeoSlugRoute: typeof SeoSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiAdminContentRoute: typeof ApiAdminContentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-policies': {
      id: '/company-policies'
      path: '/company-policies'
      fullPath: '/company-policies'
      preLoaderRoute: typeof CompanyPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more-info': {
      id: '/more-info'
      path: '/more-info'
      fullPath: '/more-info'
      preLoaderRoute: typeof MoreInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-to/$region': {
      id: '/export-to/$region'
      path: '/export-to/$region'
      fullPath: '/export-to/$region'
      preLoaderRoute: typeof ExportToRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/$slug': {
      id: '/seo/$slug'
      path: '/seo/$slug'
      fullPath: '/seo/$slug'
      preLoaderRoute: typeof SeoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content': {
      id: '/api/admin/content'
      path: '/api/admin/content'
      fullPath: '/api/admin/content'
      preLoaderRoute: typeof ApiAdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CompanyPoliciesRoute: CompanyPoliciesRoute,
  ContactRoute: ContactRoute,
  MoreInfoRoute: MoreInfoRoute,
  RequestQuoteRoute: RequestQuoteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  ExportToRegionRoute: ExportToRegionRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  SeoSlugRoute: SeoSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiAdminContentRoute: ApiAdminContentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
